# Docker Contanier File:
gitlab2:
 container_name: gitlab2
 image: gitlab/gitlab-ce:8.5.3-ce.0
 hostname: gitlab
 environment:
   GITLAB_OMNIBUS_CONFIG: |
     external_url 'http://127.0.0.1:8050'
     gitlab_rails['gitlab_shell_ssh_port'] = 522
     gitlab_registry['registry_external_url'] = 4567
 ports:
  - "8050:8050"
  - "522:22"
  - "4567:4567"
 volumes:
  - /run/media/scoday/git_lab/config:/etc/gitlab
  - /run/media/scoday/git_lab/logs:/var/log/gitlab
  - /run/media/scoday/git_lab/data:/var/opt/gitlab
 privileged: true
